# Generated by Django 5.2.7 on 2025-10-22 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True, null=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('use_start_date', models.TextField(blank=True, db_column='useStartDate', null=True)),
                ('deterioration', models.TextField(blank=True, null=True)),
                ('wall_materials', models.TextField(blank=True, db_column='wallMaterials', null=True)),
                ('plottage', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('district', models.TextField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('contacts_name', models.TextField(blank=True, db_column='contactsName', null=True)),
                ('contacts_phone', models.TextField(blank=True, db_column='contactsPhone', null=True)),
                ('contacts_email', models.TextField(blank=True, db_column='contactsEmail', null=True)),
                ('price', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'abandoned_objects',
                'managed': False,
            },
        ),
    ]
